jobs:
  build-base-image:
    permissions:
      contents: write
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: |-
          system-features = nixos-test benchmark big-parallel kvm
          access-tokens = ${{ secrets.GH_ACCESS_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v17
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: limavm-nix
    - name: Build lima-base-image
      run: |-
        nix -Lv build .#packages.${{ matrix.system }}.lima-base-image
    strategy:
      matrix:
        include:
        - runner: ubuntu-24.04
          system: x86_64-linux
        - runner: ubuntu-24.04-arm
          system: aarch64-linux
'on':
  schedule:
  - cron: 0 0 * * 0
  workflow_dispatch: {}
