jobs:
  templates-ci:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v17
      with:
        name: limavm-nix
    - name: Run templates/ci flake checks
      run: nix -Lv flake check ./templates/ci
'on':
  push:
    branches:
    - master
